apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx
  namespace: argocd # Debe ir en el namespace donde instalaste ArgoCD
spec:
  project: default
  source:
    # REEMPLAZA CON LA URL DE ESTE NUEVO REPOSITORIO GITOPS
    repoURL: 'https://github.com/Husifork/argocdtesting'
    targetRevision: HEAD # Apunta a la rama principal (main)
    path: 'apps/demo-app' # La ruta hacia donde está tu deployment.yaml
  destination:
    server: 'https://kubernetes.default.svc' # Significa "el clúster actual"
    namespace: demo-app # El namespace de tu app (se creará si no existe)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true