apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: app-db-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret-from-kv     
        volumeMounts:
        - name: secrets-store                 
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres-data
      volumes:
      - name: secrets-store                   
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-keyvault-postgres"
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc