---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: app-db-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx:alpine # Reemplaza por la imagen de tu aplicación real
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "postgres-service" # Se comunica internamente por el nombre del Service
        - name: DB_PORT
          value: "5432"
        envFrom:
        - secretRef:
            name: postgres-secret # Reutiliza las credenciales
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app-db-demo
spec:
  type: LoadBalancer # Para que Azure le asigne una IP Pública
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80