apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-postgres
  namespace: app-db-demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Usa la Managed Identity del nodo
    userAssignedIdentityID: ""            # Déjalo vacío si usas SystemAssigned
    keyvaultName: "kvtesting1"      # ← Cambia esto
    objects: |
      array:
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-db
          objectType: secret
    tenantId: "b7424ab7-14fe-4227-80a1-10549e6be624"              # ← Cambia esto
  secretObjects:
  - secretName: postgres-secret-from-kv
    type: Opaque
    data:
    - objectName: postgres-user
      key: POSTGRES_USER
    - objectName: postgres-password
      key: POSTGRES_PASSWORD
    - objectName: postgres-db
      key: POSTGRES_DB